FROM mysql
EXPOSE 3306
USER mysql
RUN chown -R mysql:mysql /var/lib/mysql
# Add the content of the sql-scripts/ directory to your image
# All scripts in docker-entrypoint-initdb.d/ are automatically
# executed during container startup
COPY ./sql-scripts/ /docker-entrypoint-initdb.d/
# VOLUME ["/var/lib/mysql"]